import os
import tempfile
import json
import yt_dlp
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# מזהה התיקייה בגוגל דרייב אליה יועלו הקבצים
DRIVE_FOLDER_ID = "1YQyaFzviICv8F-iiSjE9Sd6PrGzpBPXs"

# תוכן קובץ העוגיות שלך נשאר כאן
cookies_content = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by EditThisCookie
.youtube.com	TRUE	/	TRUE	1797610873	__Secure-1PAPISID	Hb3vhiIduY5ctFVF/AWxKpDkrodG59Mmyk
.youtube.com	TRUE	/	TRUE	1797610873	__Secure-1PSID	g.a0003gh03blpdVyoJCojW4MYZUd3_lVv_LljpQHIARmL8f5mqa5TKU3PvB49hZ0lrFD6jXJeaAACgYKAUgSARUSFQHGX2MiRUCNJBbBKpUs8OL-BmztihoVAUF8yKp21bENbnZ3nwUR9q90NrGw0076
.youtube.com	TRUE	/	TRUE	1794617766	__Secure-1PSIDCC	AKEyXzWYeyp9RYroUrc9gbGYz5R3VFgDNJMjY1QvgXMSMh094q9neh3GnH_wwRk6XCnCiJLuHg
.youtube.com	TRUE	/	TRUE	1794586873	__Secure-1PSIDTS	sidts-CjUBwQ9iI72KJyg7IjXNpzsX5W43qBGX0wGfZ2WG8g4Trz8sUzQtJRx57CL6R-nhupnIZ5vOkBAA
.youtube.com	TRUE	/	TRUE	1797610873	__Secure-3PAPISID	Hb3vhiIduY5ctFVF/AWxKpDkrodG59Mmyk
.youtube.com	TRUE	/	TRUE	1797610873	__Secure-3PSID	g.a0003gh03blpdVyoJCojW4MYZUd3_lVv_LljpQHIARmL8f5mqa5TRZKQrmrV__nNFKPAx9LQ3QACgYKAfsSARUSFQHGX2Miowg2YzMSTzBYST1Ba3HwmRoVAUF8yKoZ6DzUEWK82rZUpQ1N9DWY0076
.youtube.com	TRUE	/	TRUE	1794617766	__Secure-3PSIDCC	AKEyXzVWwIxXU8wTFAPPgwNppJJzBWKr-NLUMiiOp6BiB8vlET7E3JFp-Tdr9MQ03K4BNPR4Eg
.youtube.com	TRUE	/	TRUE	1794586873	__Secure-3PSIDTS	sidts-CjUBwQ9iI72KJyg7IjXNpzsX5W43qBGX0wGfZ2WG8g4Trz8sUzQtJRx57CL6R-nhupnIZ5vOkBAA
.youtube.com	TRUE	/	FALSE	1797610873	APISID	a0_6J1P1mbO9dmdA/Ab_Z7UNjhhdwKNzEI
.youtube.com	TRUE	/	FALSE	1797610873	HSID	Az6TeMMaHopxASF-q
.youtube.com	TRUE	/	TRUE	1790366847	LOGIN_INFO	AFmmF2swRQIhAPGLCoLUEIDnJdgL2o2hd0B7ZvuoyDBg2scR0b_fM5B5AiA3N_yJDkeeitKilOyULl64LjaQQlC4iBQ5gDRdywsO5g:QUQ3MjNmeHA5WnBxWDVTNDBnd1lJdFB4QXJLS3VuQ2JJci1HcW5EdFp2U2gtV0NGdXBKUDRuRDZMOVJBYmhCSUdEeFlHVzZNQ2U3dFdtbk8xbGV0VUFINkdieUlwWVBRRUxaaUl1TzZXNUlBemRxWENaQTVSQ2dDbmFwZFdKTXZjV3VTaGJmNlpaaHZxUkx6dk5vZFEyenNVRnA5Z3NEcFpn
.youtube.com	TRUE	/	TRUE	1797641766	PREF	tz=Asia.Jerusalem&f4=4000000&f7=100
.youtube.com	TRUE	/	TRUE	1797610873	SAPISID	Hb3vhiIduY5ctFVF/AWxKpDkrodG59Mmyk
.youtube.com	TRUE	/	FALSE	1797610873	SID	g.a0003gh03blpdVyoJCojW4MYZUd3_lVv_LljpQHIARmL8f5mqa5T_BGTqebLNHdVxZyx7PExVwACgYKAaMSARUSFQHGX2Miv5zacGYBSdQwENn-LOPc2xoVAUF8yKqcsyEAmna3BvZ_dMvySZI50076
.youtube.com	TRUE	/	FALSE	1794617766	SIDCC	AKEyXzUuWjFsf__Kg9aBx5Ho-faljy191SzkiQz6dwniBfS2w1QQ1qeM534hgwO3nZ-HqQPspA
.youtube.com	TRUE	/	TRUE	1797610873	SSID	AYHX27ueqKs-79mzF
.youtube.com	TRUE	/	FALSE	1763081770	ST-xuwub9	session_logininfo=AFmmF2swRQIhAPGLCoLUEIDnJdgL2o2hd0B7ZvuoyDBg2scR0b_fM5B5AiA3N_yJDkeeitKilOyULl64LjaQQlC4iBQ5gDRdywsO5g%3AQUQ3MjNmeHA5WnBxWDVTNDBnd1lJdFB4QXJLS3VuQ2JJci1HcW5EdFp2U2gtV0NGdXBKUDRuRDZMOVJBYmhCSUdEeFlHVzZNQ2U3dFdtbk8xbGV0VUFINkdieUlwWVBRRUxaaUl1TzZXNUlBemRxWENaQTVSQ2dDbmFwZFdKTXZjV3VTaGJmNlpaaHZxUkx6dk5vZFEyenNVRnA5Z3NEcFpn"""

def upload_to_drive(filename):
    """מעלה קובץ לתיקיית גוגל דרייב ספציפית"""
    if not filename or not os.path.exists(filename):
        print(f"הקובץ לא נמצא: {filename}")
        return
        
    try:
        # טוען את פרטי ההתחברות מתוך משתנה הסביבה (Secret)
        service_account_info = json.loads(os.getenv("GOOGLE_SERVICE_ACCOUNT"))
        creds = service_account.Credentials.from_service_account_info(
            service_account_info,
            scopes=['https://www.googleapis.com/auth/drive.file']
        )
        service = build('drive', 'v3', credentials=creds)
        
        file_metadata = {
            'name': os.path.basename(filename),
            'parents': [DRIVE_FOLDER_ID]
        }
        media = MediaFileUpload(filename)
        
        file = service.files().create(
            body=file_metadata,
            media_body=media,
            fields='id'
        ).execute()
        
        print(f"העלאה לדרייב הצליחה. File ID: {file.get('id')}")
    except Exception as e:
        print(f"אירעה שגיאה במהלך ההעלאה ל-Google Drive: {e}")


def download_media(video_url, format_choice):
    """מוריד מדיה מהקישור הנתון באמצעות yt-dlp"""
    cookie_file_path = None
    downloaded_file = None
    try:
        # יוצר קובץ עוגיות זמני
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt', encoding='utf-8') as temp_cookie_file:
            temp_cookie_file.write(cookies_content)
            cookie_file_path = temp_cookie_file.name

        ydl_opts = {
            'outtmpl': '%(title)s.%(ext)s',
            'cookiefile': cookie_file_path,
            'noplaylist': True,
        }

        if format_choice == 'mp3':
            ydl_opts['format'] = 'bestaudio/best'
            ydl_opts['postprocessors'] = [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }]
        elif format_choice == 'mp4':
            ydl_opts['format'] = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
        else:
            print(f"פורמט לא נתמך: {format_choice}. מוריד כ-MP4 כברירת מחדל.")
            ydl_opts['format'] = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=True)
            downloaded_file = ydl.prepare_filename(info)
            print(f"ההורדה הצליחה: {downloaded_file}")
            return downloaded_file

    except yt_dlp.utils.DownloadError as e:
        print(f"שגיאת הורדה מ-yt-dlp: {e}")
    except Exception as e:
        print(f"אירעה שגיאה בלתי צפויה במהלך ההורדה: {e}")
    finally:
        # מנקה את קובץ העוגיות הזמני
        if cookie_file_path and os.path.exists(cookie_file_path):
            os.remove(cookie_file_path)
    return None


if __name__ == "__main__":
    try:
        with open("link.txt", "r") as f:
            video_url = f.read().strip()
        with open("format.txt", "r") as f:
            format_choice = f.read().strip()
        
        if not video_url:
            print("הקובץ link.txt ריק. התהליך נעצר.")
        else:
            print(f"מתחיל הורדה עבור הקישור: {video_url} בפורמט: {format_choice}")
            downloaded_filename = download_media(video_url, format_choice)
            
            if downloaded_filename and os.path.exists(downloaded_filename):
                print(f"מתחיל העלאה של '{downloaded_filename}' ל-Google Drive.")
                upload_to_drive(downloaded_filename)
                
                # מנקה את הקובץ שהורד מהשרת
                os.remove(downloaded_filename)
                print(f"הקובץ המקומי נמחק: {downloaded_filename}")
            else:
                print("ההורדה נכשלה, מדלג על שלב ההעלאה.")

    except FileNotFoundError:
        print("קובץ link.txt או format.txt לא נמצא.")
    except Exception as e:
        print(f"אירעה שגיאה בתהליך הראשי: {e}")
