import os
import tempfile
import json
import yt_dlp
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# מזהה התיקייה בגוגל דרייב אליה יועלו הקבצים
DRIVE_FOLDER_ID = "1YQyaFzviICv8F-iiSjE9Sd6PrGzpBPXs"

# תוכן קובץ העוגיות שלך נשאר כאן
cookies_content = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by EditThisCookie
.youtube.com	TRUE	/	TRUE	1763085043	GPS	1
.youtube.com	TRUE	/	TRUE	1797643245	PREF	tz=Asia.Jerusalem&f4=4000000
"""

def upload_to_drive(filename):
    """מעלה קובץ לתיקיית גוגל דרייב ספציפית"""
    if not filename or not os.path.exists(filename):
        print(f"הקובץ לא נמצא: {filename}")
        return
        
    try:
        # טוען את פרטי ההתחברות מתוך משתנה הסביבה (Secret)
        service_account_info = json.loads(os.getenv("GOOGLE_SERVICE_ACCOUNT"))
        creds = service_account.Credentials.from_service_account_info(
            service_account_info,
            scopes=['https://www.googleapis.com/auth/drive.file']
        )
        service = build('drive', 'v3', credentials=creds)
        
        file_metadata = {
            'name': os.path.basename(filename),
            'parents': [DRIVE_FOLDER_ID]
        }
        media = MediaFileUpload(filename)
        
        file = service.files().create(
            body=file_metadata,
            media_body=media,
            fields='id'
        ).execute()
        
        print(f"העלאה לדרייב הצליחה. File ID: {file.get('id')}")
    except Exception as e:
        print(f"אירעה שגיאה במהלך ההעלאה ל-Google Drive: {e}")


def download_media(video_url, format_choice):
    """מוריד מדיה מהקישור הנתון באמצעות yt-dlp"""
    cookie_file_path = None
    downloaded_file = None
    try:
        # יוצר קובץ עוגיות זמני
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt', encoding='utf-8') as temp_cookie_file:
            temp_cookie_file.write(cookies_content)
            cookie_file_path = temp_cookie_file.name

        ydl_opts = {
            'outtmpl': '%(title)s.%(ext)s',
            'cookiefile': cookie_file_path,
            'noplaylist': True,
        }

        if format_choice == 'mp3':
            # מנסה להוריד MP3 ישירות. ייתכן שיוריד פורמט אודיו אחר אם MP3 לא זמין.
            ydl_opts['format'] = 'bestaudio[ext=mp3]/bestaudio'
            ydl_opts['postprocessors'] = [] # הסרת postprocessor של FFmpeg
        elif format_choice == 'mp4':
            ydl_opts['format'] = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
        else:
            print(f"פורמט לא נתמך: {format_choice}. מוריד כ-MP4 כברירת מחדל.")
            ydl_opts['format'] = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=True)
            downloaded_file = ydl.prepare_filename(info)
            print(f"ההורדה הצליחה: {downloaded_file}")
            return downloaded_file

    except yt_dlp.utils.DownloadError as e:
        print(f"שגיאת הורדה מ-yt-dlp: {e}")
    except Exception as e:
        print(f"אירעה שגיאה בלתי צפויה במהלך ההורדה: {e}")
    finally:
        # מנקה את קובץ העוגיות הזמני
        if cookie_file_path and os.path.exists(cookie_file_path):
            os.remove(cookie_file_path)
    return None


if __name__ == "__main__":
    try:
        with open("link.txt", "r") as f:
            video_url = f.read().strip()
        with open("format.txt", "r") as f:
            format_choice = f.read().strip()
        
        if not video_url:
            print("הקובץ link.txt ריק. התהליך נעצר.")
        else:
            print(f"מתחיל הורדה עבור הקישור: {video_url} בפורמט: {format_choice}")
            downloaded_filename = download_media(video_url, format_choice)
            
            if downloaded_filename and os.path.exists(downloaded_filename):
                print(f"מתחיל העלאה של '{downloaded_filename}' ל-Google Drive.")
                upload_to_drive(downloaded_filename)
                
                # מנקה את הקובץ שהורד מהשרת
                os.remove(downloaded_filename)
                print(f"הקובץ המקומי נמחק: {downloaded_filename}")
            else:
                print("ההורדה נכשלה, מדלג על שלב ההעלאה.")

    except FileNotFoundError:
        print("קובץ link.txt או format.txt לא נמצא.")
    except Exception as e:
        print(f"אירעה שגיאה בתהליך הראשי: {e}")
