import os
import tempfile
import json
import yt_dlp
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

DRIVE_FOLDER_ID = "1YQyaFzviICv8F-iiSjE9Sd6PrGzpBPXs"

cookies_content = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by EditThisCookie
.youtube.com	TRUE	/	TRUE	1797794928	__Secure-1PAPISID	XpMNUPY3FRqnSNvL/AVR3YWvmrB8Kex1db
.youtube.com	TRUE	/	TRUE	1797794928	__Secure-1PSID	g.a0003giQjh_4mKIdDIEhwlZJ-b7XrTbRvkxcfpRruKDne-tD1cDjJ25s8H8SDmnc9pGLOrrPsQACgYKAV8SARISFQHGX2MiHY-rr62GyKLehLfvU8JZ8hoVAUF8yKp4jUVnpSkIcX4UoodCXD5c0076
.youtube.com	TRUE	/	TRUE	1794770933	__Secure-1PSIDCC	AKEyXzV_ENB8Vr08NngVu6D61DSTvwPKnLq0GYpiqmavcIesg6C-S0hhLU927hvIfj4AoS5w
.youtube.com	TRUE	/	TRUE	1794770928	__Secure-1PSIDTS	sidts-CjUBwQ9iI4-7Z8qpy0AWRO62NQHJAqGm4uwkLuEw8Ubtkl_9-zxW7lkEWb-61YGfyDsMy9LsOxAA
.youtube.com	TRUE	/	TRUE	1797794928	__Secure-3PAPISID	XpMNUPY3FRqnSNvL/AVR3YWvmrB8Kex1db
.youtube.com	TRUE	/	TRUE	1797794928	__Secure-3PSID	g.a0003giQjh_4mKIdDIEhwlZJ-b7XrTbRvkxcfpRruKDne-tD1cDjaPQ8Fv-AHUlNfFQtOi-ghgACgYKAeoSARISFQHGX2MivCXmucJci0qn8FnFov-V_hoVAUF8yKq8wnGK2zial0f7wSJZTqcU0076
.youtube.com	TRUE	/	TRUE	1794770933	__Secure-3PSIDCC	AKEyXzXyhH3Np-CVW4UChNtGPNsON5OgCyJjpkJeRYhkU4LD7cU1WsiIugNAY1TQGIkk81eA
.youtube.com	TRUE	/	TRUE	1794770928	__Secure-3PSIDTS	sidts-CjUBwQ9iI4-7Z8qpy0AWRO62NQHJAqGm4uwkLuEw8Ubtkl_9-zxW7lkEWb-61YGfyDsMy9LsOxAA
.youtube.com	TRUE	/	FALSE	1797794928	APISID	VldhycZGBnXCbHB_/AhpDg30ZZnfGFNAp3
.youtube.com	TRUE	/	FALSE	1797794928	HSID	ABIpRz9pNG4TMUc7D
.youtube.com	TRUE	/	TRUE	1797794929	LOGIN_INFO	AFmmF2swRgIhAKeQ36V9klg8plkacAzRH9ernra3fBGEK3rCkrnvijkJAiEAlOA2f8aWRwwAV4o0EQa-f9VLkQnfz4__BvNwBX0ejYM:QUQ3MjNmd0lxTUZPdURnZWp6R0dVWkpmeWs1Z1lud3d0SHFGMEo3c1RzZ19TYS1uaVU2aDd6N3lYMmFBbHZ6aUlGS2lVWjJ6RU16S0JSWWJSUVhtZzVKUVlFNElHODI3M1diNWRsTkRuSzJ4NDQ4OVgxT095X1N2Snlnbnh4QnItVFpySHRsTjNXd05zdnNXX19GanJNdTVkZmlTX3F1bElB
.youtube.com	TRUE	/	TRUE	1797794932	PREF	tz=Asia.Jerusalem&f4=4000000
.youtube.com	TRUE	/	TRUE	1797794928	SAPISID	XpMNUPY3FRqnSNvL/AVR3YWvmrB8Kex1db
.youtube.com	TRUE	/	FALSE	1797794928	SID	g.a0003giQjh_4mKIdDIEhwlZJ-b7XrTbRvkxcfpRruKDne-tD1cDjGHmyKe2pL0r-54Hb4o_EIgACgYKAbQSARISFQHGX2MiDTffB-VYUXtbmmll_V7CTxoVAUF8yKogFU5vg841ku_b8-5dCypr0076
.youtube.com	TRUE	/	FALSE	1794770933	SIDCC	AKEyXzUFQ-azfwWAy1ZFCmNjf6k4bhcgHhD4nUiIdkf8NAGHt4s8uA1LSD4R6QvFLzeIV3ardw
.youtube.com	TRUE	/	TRUE	1797794928	SSID	AlKp-u91aDiVFxyAO
.youtube.com	TRUE	/	FALSE	1763234937	ST-xuwub9	session_logininfo=AFmmF2swRgIhAKeQ36V9klg8plkacAzRH9ernra3fBGEK3rCkrnvijkJAiEAlOA2f8aWRwwAV4o0EQa-f9VLkQnfz4__BvNwBX0ejYM%3AQUQ3MjNmd0lxTUZPdURnZWp6R0dVWkpmeWs1Z1lud3d0SHFGMEo3c1RzZ19TYS1uaVU2aDd6N3lYMmFBbHZ6aUlGS2lVWjJ6RU16S0JSWWJSUVhtZzVKUVlFNElHODI3M1diNWRsTkRuSzJ4NDQ4OVgxT095X1N2Snlnbnh4QnItVFpySHRsTjNXd05zdnNXX19GanJNdTVkZmlTX3F1bElB
"""

def upload_to_drive(filename):
    if not filename or not os.path.exists(filename):
        print(f"הקובץ לא נמצא: {filename}")
        return
    try:
        service_account_info = json.loads(os.getenv("GOOGLE_SERVICE_ACCOUNT"))
        creds = service_account.Credentials.from_service_account_info(
            service_account_info,
            scopes=['https://www.googleapis.com/auth/drive.file']
        )
        service = build('drive', 'v3', credentials=creds)
        file_metadata = {'name': os.path.basename(filename), 'parents': [DRIVE_FOLDER_ID]}
        media = MediaFileUpload(filename)
        file = service.files().create(body=file_metadata, media_body=media, fields='id').execute()
        print(f"העלאה לדרייב הצליחה. File ID: {file.get('id')}")
    except Exception as e:
        print(f"אירעה שגיאה במהלך ההעלאה ל-Google Drive: {e}")

def download_media(video_url, format_choice):
    cookie_file_path = None
    final_filename = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt', encoding='utf-8') as temp_cookie_file:
            temp_cookie_file.write(cookies_content)
            cookie_file_path = temp_cookie_file.name

        ydl_opts = {
            'outtmpl': '%(title)s.%(ext)s',
            'cookiefile': cookie_file_path,
            'noplaylist': True,
        }

        if format_choice == 'mp3':
            # --- התיקון המרכזי ---
            # מוריד את האודיו הטוב ביותר (לא משנה הפורמט) וממיר ל-MP3
            print("מגדיר הורדה לאודיו בלבד והמרה ל-MP3.")
            ydl_opts['format'] = 'bestaudio/best'
            ydl_opts['postprocessors'] = [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }]
        else: # ברירת מחדל ל-MP4
            print("מגדיר הורדה לווידאו MP4.")
            ydl_opts['format'] = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=True)
            base, _ = os.path.splitext(ydl.prepare_filename(info))
            if format_choice == 'mp3':
                final_filename = base + '.mp3'
            else:
                final_filename = base + '.mp4'
            
            print(f"ההורדה וההמרה הסתיימו. שם קובץ סופי: {final_filename}")
            return final_filename
    except Exception as e:
        print(f"אירעה שגיאה בלתי צפויה במהלך ההורדה: {e}")
    finally:
        if cookie_file_path and os.path.exists(cookie_file_path):
            os.remove(cookie_file_path)
    return None

if __name__ == "__main__":
    try:
        with open("link.txt", "r") as f: video_url = f.read().strip()
        with open("format.txt", "r") as f: format_choice = f.read().strip()
        
        if not video_url:
            print("הקובץ link.txt ריק. התהליך נעצר.")
        else:
            print(f"מתחיל תהליך עבור הקישור: {video_url} בפורמט: {format_choice}")
            downloaded_filename = download_media(video_url, format_choice)
            if downloaded_filename and os.path.exists(downloaded_filename):
                print(f"מתחיל העלאה של '{downloaded_filename}' ל-Google Drive.")
                upload_to_drive(downloaded_filename)
                os.remove(downloaded_filename)
                print(f"הקובץ המקומי נמחק: {downloaded_filename}")
            else:
                print("ההורדה נכשלה, מדלג על שלב ההעלאה.")
    except Exception as e:
        print(f"אירעה שגיאה בתהליך הראשי: {e}")
